#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Last updated: on May 28 11:12 2023

@author: Ethan Masters

Purpose: PV Project Constants, used to store constant variables
    for repititive use.

Python Version: Python 3.10.11 
"""

DATA_SUMMARY_DICT = {
    'GlobalIR': {
        'count': 5354753,
        'mean': 122.1875,
        'std': 224.0314,
        'min': 0.0,
        '25%': 0.0,
        '50%': 0.0,
        '75%': 136.0,
        'max': 1458.0
    },
    'DirectIR': {
        'count': 5354753,
        'mean': 53.85663,
        'std': 89.27746,
        'min': 0.0,
        '25%': 0.0,
        '50%': 0.0,
        '75%': 81.9,
        'max': 729.4
    },
    'DiffuseIR': {
        'count': 5354753,
        'mean': 68.3309,
        'std': 168.9914,
        'min': 0.0,
        '25%': 0.0,
        '50%': 0.0,
        '75%': 5.7,
        'max': 1159.7
    },
    'WindSpeed': {
        'count': 5095833,
        'mean': 1.214944,
        'std': 1.176539,
        'min': 0.0,
        '25%': 0.17,
        '50%': 1.04,
        '75%': 1.755,
        'max': 10.0
    },
    'Temperature': {
        'count': 5095839,
        'mean': 11.07429,
        'std': 8.145981,
        'min': -11.5,
        '25%': 5.0,
        '50%': 9.9,
        '75%': 16.2,
        'max': 41.3
    }
}

DATA_FILE_OPTIONS = {
    "years": ["2019", "2020", "2021", "2022", "2023"],
    "months": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    "file_types": ["Deger", "Fixed", "Irradiance"]
}

FILE_OPTIONS_COMBO = [
    ('Deger', '2019', 'nov'),
    ('Deger', '2019', 'oct'),
    ('Fixed', '2019', 'sep'),
    ('Irradiance', '2019', 'dec'),
    ('Irradiance', '2019', 'nov'),
    ('Irradiance', '2019', 'oct'),
    ('Irradiance', '2019', 'sep'),
    ('Deger', '2020', 'apr'),
    ('Deger', '2020', 'aug'),
    ('Deger', '2020', 'feb'),
    ('Deger', '2020', 'jan'),
    ('Deger', '2020', 'jul'),
    ('Deger', '2020', 'jun'),
    ('Deger', '2020', 'mar'),
    ('Deger', '2020', 'sep'),
    ('Deger', '2020', 'dec'),
    ('Deger', '2020', 'nov'),
    ('Deger', '2020', 'oct'),
    ('Fixed', '2020', 'apr'),
    ('Fixed', '2020', 'aug'),
    ('Fixed', '2020', 'feb'),
    ('Fixed', '2020', 'jan'),
    ('Fixed', '2020', 'jul'),
    ('Fixed', '2020', 'jun'),
    ('Fixed', '2020', 'mar'),
    ('Fixed', '2020', 'sep'),
    ('Fixed', '2020', 'dec'),
    ('Fixed', '2020', 'nov'),
    ('Fixed', '2020', 'oct'),
    ('Irradiance', '2020', 'apr'),
    ('Irradiance', '2020', 'aug'),
    ('Irradiance', '2020', 'dec'),
    ('Irradiance', '2020', 'feb'),
    ('Irradiance', '2020', 'jan'),
    ('Irradiance', '2020', 'jul'),
    ('Irradiance', '2020', 'jun'),
    ('Irradiance', '2020', 'mar'),
    ('Irradiance', '2020', 'may'),
    ('Irradiance', '2020', 'nov'),
    ('Irradiance', '2020', 'oct'),
    ('Irradiance', '2020', 'sep'),
    ('Deger', '2021', 'apr'),
    ('Deger', '2021', 'aug'),
    ('Deger', '2021', 'dec'),
    ('Deger', '2021', 'feb'),
    ('Deger', '2021', 'jan'),
    ('Deger', '2021', 'jul'),
    ('Deger', '2021', 'jun'),
    ('Deger', '2021', 'mar'),
    ('Deger', '2021', 'may'),
    ('Deger', '2021', 'nov'),
    ('Deger', '2021', 'oct'),
    ('Deger', '2021', 'sep'),
    ('Fixed', '2021', 'apr'),
    ('Fixed', '2021', 'aug'),
    ('Fixed', '2021', 'dec'),
    ('Fixed', '2021', 'feb'),
    ('Fixed', '2021', 'jan'),
    ('Fixed', '2021', 'jul'),
    ('Fixed', '2021', 'jun'),
    ('Fixed', '2021', 'mar'),
    ('Fixed', '2021', 'may'),
    ('Fixed', '2021', 'nov'),
    ('Fixed', '2021', 'oct'),
    ('Fixed', '2021', 'sep'),
    ('Irradiance', '2021', 'apr'),
    ('Irradiance', '2021', 'feb'),
    ('Irradiance', '2021', 'jan'),
    ('Irradiance', '2021', 'jul'),
    ('Irradiance', '2021', 'jun'),
    ('Irradiance', '2021', 'mar'),
    ('Irradiance', '2021', 'may'),
    ('Irradiance', '2021', 'aug'),
    ('Irradiance', '2021', 'dec'),
    ('Irradiance', '2021', 'nov'),
    ('Irradiance', '2021', 'oct'),
    ('Irradiance', '2021', 'sep'),
    ('Deger', '2022', 'apr'),
    ('Deger', '2022', 'aug'),
    ('Deger', '2022', 'dec'),
    ('Deger', '2022', 'feb'),
    ('Deger', '2022', 'jan'),
    ('Deger', '2022', 'jul'),
    ('Deger', '2022', 'jun'),
    ('Deger', '2022', 'mar'),
    ('Deger', '2022', 'may'),
    ('Deger', '2022', 'nov'),
    ('Deger', '2022', 'oct'),
    ('Deger', '2022', 'sep'),
    ('Fixed', '2022', 'apr'),
    ('Fixed', '2022', 'aug'),
    ('Fixed', '2022', 'dec'),
    ('Fixed', '2022', 'feb'),
    ('Fixed', '2022', 'jan'),
    ('Fixed', '2022', 'jul'),
    ('Fixed', '2022', 'jun'),
    ('Fixed', '2022', 'mar'),
    ('Fixed', '2022', 'may'),
    ('Fixed', '2022', 'nov'),
    ('Fixed', '2022', 'oct'),
    ('Fixed', '2022', 'sep'),
    ('Irradiance', '2022', 'apr'),
    ('Irradiance', '2022', 'aug'),
    ('Irradiance', '2022', 'dec'),
    ('Irradiance', '2022', 'feb'),
    ('Irradiance', '2022', 'jan'),
    ('Irradiance', '2022', 'jul'),
    ('Irradiance', '2022', 'jun'),
    ('Irradiance', '2022', 'mar'),
    ('Irradiance', '2022', 'may'),
    ('Irradiance', '2022', 'nov'),
    ('Irradiance', '2022', 'oct'),
    ('Irradiance', '2022', 'sep'),
    ('Deger', '2023', 'feb'),
    ('Deger', '2023', 'jan'),
    ('Deger', '2023', 'mar'),
    ('Fixed', '2023', 'feb'),
    ('Fixed', '2023', 'jan'),
    ('Fixed', '2023', 'mar'),
    ('Irradiance', '2023', 'feb'),
    ('Irradiance', '2023', 'jan'),
    ('Irradiance', '2023', 'mar'),
]

MONTH_DICT = {
    "January": "jan",
    "February": "feb",
    "March": "mar",
    "April": "apr",
    "May": "may",
    "June": "jun",
    "July": "jul",
    "August": "aug",
    "September": "sep",
    "October": "oct",
    "November": "nov",
    "December": "dec"
}

MONTH_DICT_INVERTED = {
    "jan": "January",
    "feb": "February",
    "mar": "March",
    "apr": "April",
    "may": "May",
    "jun": "June",
    "jul": "July",
    "aug": "August",
    "sep": "September",
    "oct": "October",
    "nov": "November",
    "dec": "December"
}

COL_NAMES = {
    'Irradiance' : ['GlobalIR','DirectIR','DiffuseIR','WindSpeed','Temperature'],
    'Deger' : ['MonoSi_Vin','MonoSi_Iin','MonoSi_Vout','MonoSi_Iout','PolySi_Vin','PolySi_Iin','PolySi_Vout','PolySi_Iout','TFSi_a_Vin','TFSi_a_Iin','TFSi_a_Vout','TFSi_a_Iout','TFcigs_Vin','TFcigs_Iin','TFcigs_Vout','TFcigs_Iout','TempF_Mono','TempF_Poly','TempF_Amor','TempF_Cigs'],
    'Fixed' : ['MonoSi_Vin', 'MonoSi_Iin', 'MonoSi_Vout', 'MonoSi_Iout', 'PolySi_Vin', 'PolySi_Iin', 'PolySi_Vout', 'PolySi_Iout', 'TFSi_a_Vin', 'TFSi_a_Iin', 'TFSi_a_Vout', 'TFSi_a_Iout', 'TFcigs_Vin', 'TFcigs_Iin', 'TFcigs_Vout', 'TFcigs_Iout', 'TempF_Mono', 'TempF_Poly', 'TempF_Amor', 'TempF_Cigs'],
    'Uknown' : []
}

COL_NAMES_ORG = {
    'Deger' : [
                "DayID",
                "TimeID",
                "MonoSi_Vin",
                "MonoSi_Iin",
                "MonoSi_Vout",
                "MonoSi_Iout",
                "PolySi_Vin",
                "PolySi_Iin",
                "PolySi_Vout",
                "PolySi_Iout",
                "TFSi_a_Vin",
                "TFSi_a_Iin",
                "TFSi_a_Vout",
                "TFSi_a_Iout",
                "TFcigs_Vin",
                "TFcigs_Iin",
                "TFcigs_Vout",
                "TFcigs_Iout",
                "Temp_Mono",
                "Temp_Poly",
                "Temp_Amor",
                "Temp_Cigs"
            ],
    'Fixed' : [
                "DayID",
                "TimeID",
                "MonoSi_Vin",
                "MonoSi_Iin",
                "MonoSi_Vout",
                "MonoSi_Iout",
                "PolySi_Vin",
                "PolySi_Iin",
                "PolySi_Vout",
                "PolySi_Iout",
                "TFSi_a_Vin",
                "TFSi_a_Iin",
                "TFSi_a_Vout",
                "TFSi_a_Iout",
                "TFcigs_Vin",
                "TFcigs_Iin",
                "TFcigs_Vout",
                "TFcigs_Iout",
                "TempF_Mono",
                "TempF_Poly",
                "TempF_Amor",
                "TempF_Cigs"
            ],
    'Irradiance' : [
                "DayID",
                "TimeID",
                "GlobalIR",
                "DiffuseIR",
                "DirectIR",
                "WindSpeed",
                "Temperature"
            ]
}